name: Backport
on:
    pull_request:
        types:
            - closed
            - labeled

jobs:
    backport:
        runs-on: ubuntu-latest
        name: Backport
        steps:
            - name: Backport
              uses: radcortez/backport-action@main
              with:
                  github_token: ${{ secrets.GH_API_SECRET }}
              env:
                  GIT_COMMITTER_NAME: ${{ env.GITHUB_ACTOR }}
                  GIT_COMMITTER_EMAIL: noreply@github.com
